
build:
  stage: build
  image: docker:latest
  before_script:
    - echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_USER} --password-stdin
  script:
    - KEYS=$(cat keys.txt)
    - docker build -t jitesoft/lighttpd --build-arg KEYS="${KEYS}" -q --no-cache .
    - docker push jitesoft/lighttpd:latest
