stages:
    - lighttpd
    - fpm

build:lighttpd:
  stage: lighttpd
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_USER} --password-stdin
  script:
    - KEYS=$(cat keys.txt)
    - docker build -t jitesoft/lighttpd --build-arg KEYS="${KEYS}" --no-cache .
    - docker push jitesoft/lighttpd:latest


build:lighttpd:fpm:
  stage: fpm
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_USER} --password-stdin
  script:
    - docker build -t jitesoft/lighttpd:fpm --no-cache cgi
    - docker push jitesoft/lighttpd:fpm