include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/container_scan-v2.yml

stages:
    - lighttpd
    - fpm
    - extra
    - scan

variables:
  PLATFORMS: "linux/arm64,linux/amd64,linux/386,linux/ppc64le,linux/s390x"

build:lighttpd:
  stage: lighttpd
  image: registry.gitlab.com/jitesoft/dockerfiles/misc:latest
  script:
    - VERSION=$(wget -qO- https://download.lighttpd.net/lighttpd/releases-1.4.x/ | grep -oP "(?<=<a href=\"lighttpd-)([0-9]{0,3}[.][0-9]{0,3}[.][0-9]{0,3})" | sort -r -u - | awk 'NR==1{print $1}')
    - KEYS=$(cat keys.txt)
    - TAG_LIST=$(helper taglist "${CI_REGISTRY_IMAGE},jitesoft/lighttpd" "latest,${VERSION}")
    - docker buildx build --platform ${PLATFORMS} --progress plain --push ${TAG_LIST} --build-arg KEYS="${KEYS}" --build-arg VERSION=${VERSION} .
  tags: [ jitesoft, buildx, amd64, arm64, x86, ppc64le, s390x ]

build:lighttpd:fpm:
  needs:
    - build:lighttpd
  stage: fpm
  image: registry.gitlab.com/jitesoft/dockerfiles/misc:latest
  script:
    - VERSION=$(wget -qO- https://download.lighttpd.net/lighttpd/releases-1.4.x/ | grep -oP "(?<=<a href=\"lighttpd-)([0-9]{0,3}[.][0-9]{0,3}[.][0-9]{0,3})" | sort -r -u - | awk 'NR==1{print $1}')
    - TAG_LIST=$(helper taglist "${CI_REGISTRY_IMAGE},jitesoft/lighttpd" "latest-fpm,${VERSION}-fpm,fpm")
    - cd cgi
    - docker buildx build --platform ${PLATFORMS} --progress plain --push ${TAG_LIST} .
  tags: [ jitesoft, buildx, amd64, arm64, x86, ppc64le, s390x ]

push:none-multi-arch:
  stage: extra
  image: registry.gitlab.com/jitesoft/dockerfiles/misc:latest
  script:
    - VERSION=$(wget -qO- https://download.lighttpd.net/lighttpd/releases-1.4.x/ | grep -oP "(?<=<a href=\"lighttpd-)([0-9]{0,3}[.][0-9]{0,3}[.][0-9]{0,3})" | sort -r -u - | awk 'NR==1{print $1}')
    - docker pull ${CI_REGISTRY_IMAGE}:latest
    - helper multitag ${CI_REGISTRY_IMAGE}:latest quay.io/jitesoft/lighttpd:latest quay.io/jitesoft/lighttpd:${VERSION}
    - helper multipush quay.io/jitesoft/lighttpd:latest quay.io/jitesoft/lighttpd:${VERSION}
    - docker pull ${CI_REGISTRY_IMAGE}:fpm
    - helper multitag ${CI_REGISTRY_IMAGE}:latest quay.io/jitesoft/lighttpd:latest-fpm quay.io/jitesoft/lighttpd:${VERSION}-fpm quay.io/jitesoft/lighttpd:fpm
    - helper multipush quay.io/jitesoft/lighttpd:latest-fpm quay.io/jitesoft/lighttpd:${VERSION}-fpm quay.io/jitesoft/lighttpd:fpm

scan:
  needs:
    - build:lighttpd
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}:latest"
    GIT_STRATEGY: none
