stages:
    - lighttpd
    - fpm

variables:
  IMAGE_NAME: "jitesoft/lighttpd"
  VERSION: 1.4.49

build:lighttpd:
  stage: lighttpd
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache grep curl
    - echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_USER} --password-stdin
    - echo ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token registry.gitlab.com --password-stdin
  script:
    - KEYS=$(cat keys.txt)
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} --label="lighttpd.version=${VERSION}" --build-arg KEYS="${KEYS}" --build-arg VERSION=${VERSION} --no-cache .
    - TAGS="latest ${VERSION}"
    - |
      for tag in $TAGS; do
        docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} ${IMAGE_NAME}:${tag}
        docker tag ${CI_REGISTRY_IMAGE}:${tag}
        docker push ${IMAGE_NAME}:${tag}
        docker push ${CI_REGISTRY_IMAGE}:${tag}
      done
    - docker push jitesoft/lighttpd:latest


build:lighttpd:fpm:
  stage: fpm
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache grep curl
    - echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_USER} --password-stdin
    - echo ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token registry.gitlab.com --password-stdin
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} --label="lighttpd.fpm=active" --network host --no-cache cgi
    - TAGS="latest-fpm ${VERSION}-fpm fpm"
    - |
      for tag in $TAGS; do
        docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} ${IMAGE_NAME}:${tag}
        docker tag ${CI_REGISTRY_IMAGE}:${tag}
        docker push ${IMAGE_NAME}:${tag}
        docker push ${CI_REGISTRY_IMAGE}:${tag}
      done
