include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/container_scan.yml

stages:
    - lighttpd
    - fpm
    - scan

build:lighttpd:
  stage: lighttpd
  image: registry.gitlab.com/jitesoft/dockerfiles/docker:latest
  before_script:
    - apk add --no-cache grep wget grep
    - VERSION=$(wget -qO- https://download.lighttpd.net/lighttpd/releases-1.4.x/ | grep -oP "(?<=<a href=\"lighttpd-)([0-9]{0,3}[.][0-9]{0,3}[.][0-9]{0,3})" | sort -r -u - | awk 'NR==1{print $1}')
  script:
    - KEYS=$(cat keys.txt)
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} --label="com.jitesoft.app.lighttpd.version=${VERSION}" --build-arg KEYS="${KEYS}" --build-arg VERSION=${VERSION} --no-cache .
    - TAGS="latest ${VERSION}"
    - |
      for tag in $TAGS; do
        docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} jitesoft/lighttpd:${tag}
        docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} quay.io/jitesoft/lighttpd:${tag}
        docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} ${CI_REGISTRY_IMAGE}:${tag}
        docker push jitesoft/lighttpd:${tag}
        docker push quay.io/jitesoft/lighttpd:${tag}
        docker push ${CI_REGISTRY_IMAGE}:${tag}
      done

build:lighttpd:fpm:
  needs:
    - build:lighttpd
  stage: fpm
  image: registry.gitlab.com/jitesoft/dockerfiles/docker:latest
  before_script:
    - VERSION=$(wget -qO- https://download.lighttpd.net/lighttpd/releases-1.4.x/ | grep -oP "(?<=<a href=\"lighttpd-)([0-9]{0,3}[.][0-9]{0,3}[.][0-9]{0,3})" | sort -r -u - | awk 'NR==1{print $1}')
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} --label="com.jitesoft.app.lighttpd.fpm=active" --network host --no-cache cgi
    - TAGS="latest-fpm ${VERSION}-fpm fpm"
    - |
      for tag in $TAGS; do
        docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} jitesoft/lighttpd:${tag}
        docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} quay.io/jitesoft/lighttpd:${tag}
        docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} ${CI_REGISTRY_IMAGE}:${tag}
        docker push jitesoft/lighttpd:${tag}
        docker push quay.io/jitesoft/lighttpd:${tag}
        docker push ${CI_REGISTRY_IMAGE}:${tag}
      done

scan:
  stage: scan
  needs:
    - build:lighttpd
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}:latest"
    GIT_STRATEGY: none
